---
title: "Prediction"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

_Agyey Arya_   
_October 12, 2019_

```{r init, include=FALSE}
library(lattice)
library(caret)
library(ggplot2)
library(rpart.plot)
```

```{r load}
training_data <- read.csv('pml-training.csv', na.strings = c("","NA", "#DIV/0!"))
test_data <- read.csv('pml-testing.csv', na.strings = c("","NA", "#DIV/0!"))
```

## Data Cleaing

# Removing data points with majority NAs and verifying the output

```{r clean}
clnColumnIndex <- colSums(is.na(training_data))/nrow(training_data) < 0.95
clean_training_data <- training_data[,clnColumnIndex]
colSums(is.na(clean_training_data))/nrow(clean_training_data)
```

Removing Column 1 through 7, as they are unrelated to the model
```{r remove}
clean_training_data <- clean_training_data[,-c(1:7)]
clean_test_data <- test_data[,-c(1:7)]
```

Creating training, test and cv sets
```{r sets}
inTrainIndex <- createDataPartition(clean_training_data$classe, p=0.75)[[1]]
training_training_data <- clean_training_data[inTrainIndex,]
training_crossval_data <- clean_training_data[-inTrainIndex,]
allNames <- names(clean_training_data)
clean_test_data <- test_data[,allNames[1:52]]
```

## Decision Tree

```{r tree}
decisionTreeMod <- train(classe ~., method='rpart', data=training_training_data)
decisionTreePrediction <- predict(decisionTreeMod, training_crossval_data)
confusionMatrix(training_crossval_data$classe, decisionTreePrediction)
rpart.plot(decisionTreeMod$finalModel)
```

## Random Forest

```{r forest}
rfMod <- train(classe ~., method='rf', data=training_training_data, ntree=128)
rfPrediction <- predict(rfMod, training_crossval_data)
confusionMatrix(training_crossval_data$classe, rfPrediction)
```

## Results

```{r predict}
predict(rfMod, clean_test_data)
```
